-- Supabase schema for Metaverse Morocco Map
create table if not exists public.cities (
  id text primary key,
  name_en text not null,
  name_fr text not null,
  name_ar text not null,
  lng double precision not null,
  lat double precision not null
);

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  city_id text not null references public.cities(id) on delete cascade,
  name text not null,
  description text,
  owner_id uuid references auth.users(id)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null,
  description text,
  price_cents integer not null check (price_cents >= 0),
  image_url text
);

create table if not exists public.eco_projects (
  id uuid primary key default gen_random_uuid(),
  city_id text not null references public.cities(id) on delete cascade,
  title text not null,
  summary text,
  category text check (category in ('solar','wind','water','recycling','conservation')),
  website text
);

create table if not exists public.attractions (
  id uuid primary key default gen_random_uuid(),
  city_id text not null references public.cities(id) on delete cascade,
  title text not null,
  summary text,
  image_url text
);

create table if not exists public.profiles (
  id uuid primary key,
  username text unique,
  avatar_url text
);

-- Realtime chat/messages (public channel by city)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  city_id text not null references public.cities(id) on delete cascade,
  user_id uuid references auth.users(id),
  username text,
  content text not null,
  created_at timestamp with time zone default now()
);

-- RLS
alter table public.profiles enable row level security;
create policy "Profiles are readable by everyone" on public.profiles for select using (true);
create policy "Profiles are insertable by user" on public.profiles for insert with check (auth.uid() = id);
create policy "Profiles are updatable by owner" on public.profiles for update using (auth.uid() = id);

alter table public.messages enable row level security;
create policy "Messages readable by all" on public.messages for select using (true);
create policy "Messages insert by authenticated" on public.messages for insert with check (auth.role() = 'authenticated');

alter table public.stores enable row level security;
create policy "Stores readable by all" on public.stores for select using (true);
create policy "Stores manageable by owner" on public.stores for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

alter table public.products enable row level security;
create policy "Products readable by all" on public.products for select using (true);
create policy "Products manageable via store owner" on public.products for all using (exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid())) with check (exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid()));

alter table public.cities enable row level security;
create policy "Cities readable by all" on public.cities for select using (true);

alter table public.eco_projects enable row level security;
create policy "Eco projects readable by all" on public.eco_projects for select using (true);

-- Functions/triggers to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, split_part(new.email, '@', 1))
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
